name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.11.0+2 
publish_to: none

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android_camerax 

dependencies:
  camera_android_camerax:  
    git:
      url: https://github.com/dothanhbinh41/camera_android_camerax
      ref: main  # Nhánh, tag, hoặc commit  
  camera_platform_interface: 
    git:
      url: https://github.com/dothanhbinh41/camera_platform_interface
      ref: main  # Nhánh, tag, hoặc commit  
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  plugin_platform_interface: ^2.1.7

topics:
  - camera
